/**
 * Shared Postgres column vocabulary — the mirror of `./sqlite.ts`. Same idea: every table
 * is assembled from these shared building blocks so the two dialect schemas can't drift.
 * Postgres has native types, so the mapping is direct: uuid -> uuid, timestamp ->
 * timestamptz. Column names and semantics match the SQLite side exactly; `../parity.test.ts`
 * enforces that.
 */

import { timestamp, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";

/** Primary key: a native uuid, generated by the database. */
export const id = () => uuid("id").primaryKey().defaultRandom();

/** `created_at` / `updated_at` as timezone-aware timestamps, surfaced as `Date`. */
export const audit = () => ({
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date()),
});

/** Soft-delete marker — history is never hard-deleted (ARCHITECTURE.md §5). */
export const deletedAt = () =>
  timestamp("deleted_at", { withTimezone: true, mode: "date" });

/**
 * `org_id` — the Postgres mirror of the SQLite `orgId` helper. A nullable foreign key to
 * the owning organization, `SET NULL` on delete and never cascade (ARCHITECTURE.md §5).
 * Pass the target column as a thunk: `orgId(() => organizations.id)`.
 */
export const orgId = (ref: () => AnyPgColumn) =>
  uuid("org_id").references(ref, { onDelete: "set null" });
