/**
 * Shared Postgres column vocabulary (ADR-0006) — the dialect-mirror of `./sqlite.ts`.
 * Postgres has native types, so: uuid -> uuid, timestamp -> timestamptz. Column names
 * and semantics match the SQLite side exactly; the parity test enforces that.
 */

import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key: a native uuid, generated by the database. */
export const id = () => uuid("id").primaryKey().defaultRandom();

/** `created_at` / `updated_at` as timezone-aware timestamps, surfaced as `Date`. */
export const audit = () => ({
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date()),
});

/** Soft-delete marker — history is never hard-deleted (ARCHITECTURE.md §5). */
export const deletedAt = () =>
  timestamp("deleted_at", { withTimezone: true, mode: "date" });
